server:
  port: 8083

spring:
  application:
    name: detection-service
  datasource:
    url: jdbc:postgresql://postgres:5432/splunk_db
    username: splunk_user
    password: splunk_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: detection-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

kafka:
  topic:
    logs: log-events

ai:
  service:
    url: http://ai-service:8000
