server:
  port: 8082

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://postgres:5432/splunk_db
    username: splunk_user
    password: splunk_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

kafka:
  topic:
    logs: log-events
